### ISSUE TITLE
Add the possibility to unpack DLL modules

### ISSUE THREAD

**Issue by poxyran** [hasherezade/mal_unpack#3]
Hello, 

it would be useful to include the possibility to directly unpack DLLs.

**Comment by hasherezade** [comment]
@poxyran : there is a possibility to unpack DLLs, you just need to use an external loader. It can be rundll, or my custom loader: [dll_load](https://github.com/hasherezade/pe_utils/tree/master/dll_load).
You can then unpack the DLL in the following way:

```cmd
mal_unpack /exe dll_load32.exe /cmd my_dll.dll /timeout {your timeout}
```

**Comment by poxyran** [comment]
Great, I didn't know that. thanks! you can close the issue now.
