### ISSUE TITLE
Not working for Bumblebee

### ISSUE THREAD

**Issue by nullcharb** [hasherezade/mal_unpack#5]
Hi Hasherezade,

Many thanks for creating such an awesome tool. This along with the driver is such a great tool to use.

I am testing malunpack with dll's. I have used it to unpack qakbot sucessfully, but it does not seem to work for bumblebee. 

I hash I am using is: FED9BC8DF9141F8F8F7A9203BC26B5B22123C154702FCD625379F2F7ECD31CB2

The export for the sample is : hKOgtkmCis

While debugging I see that the sample does not use VirtualAlloc. If I set a break point on VirtualAlloc, when it hits the breakpoint, the ERW section with mapped PE file is already created. Maybe that is the case why the unpacking is failing.

Any suggestions would be appreciated.

**Comment by hasherezade** [comment]
hi @nullcharb !
I am glad that you are enjoying using mal_unpack!
Thank you for reporting, I will check it soon and let you know.

**Comment by hasherezade** [comment]
@nullcharb  - I checked it, and I was able to dump the  payload, with mal_unpack (with driver and without), as well with the PE-sieve (plain version).

![unpacked1](https://github.com/hasherezade/mal_unpack/assets/3115348/cbbe2c19-917c-449c-afef-49802dee59eb)

This is what I've got:

+ [process_9588.zip](https://github.com/hasherezade/mal_unpack/files/11480548/process_9588.zip) - password: `infected`
+ at [VirusTotal](https://www.virustotal.com/gui/file/7876e8dc0a06ab3ffd61d0b040327ac960d33543beafa2761b69b7b6c7935cec/detection)

This was my commandline (for the original DLL):
```cmd
mal_unpack.exe /exe "C:\Windows\System32\rundll32.exe" /cmd "bumble.dll,#1" /timeout 100000
```
And for the Exe version (I converted the DLL into an Exe, by the method 1 described [here](https://hshrzd.wordpress.com/2016/07/21/how-to-turn-a-dll-into-a-standalone-exe/).)

```cmd
mal_unpack.exe /exe bumble.exe /timeout 100000
```

Please try again and let me know...

**Comment by nullcharb** [comment]
You are right, today I tried it with 60 second timeout and it worked. 

Thanks a lot for your quick feedback.


Thanks,

Ahmed.
